### ISSUE TITLE
перестал работать

### ISSUE THREAD

**Issue by voprosnik** [vs-marshall/Chione#3]
перестал работать выдает ошибку Traceback (most recent call last):
  File "main.py", line 12, in <module>
  File "main.py", line 8, in main
  File "gui\gui_manager.py", line 77, in __init__
  File "utils\options.py", line 51, in load_settings
  File "utils\options.py", line 12, in load_logic
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 что делать

**Comment by LennardFe** [comment]
**English:** Try deleting your "options.json" file which keeps track of your settings. For some reason this file can become corrupted, which results in Chione not being able to start. You can normally find this file in the following path: "C:/User/YourUserName/options.json"

**Русский (DeepL Перевод):** Попробуйте удалить файл «options.json», в котором хранятся ваши настройки. По некоторым причинам этот файл может быть поврежден, что приводит к невозможности запуска Chione. Обычно вы можете найти этот файл по следующему пути: "C:/Пользователи/ВашеИмяПользователя/options.json".
